import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import '@fortawesome/fontawesome-free/css/all.min.css';
import {GoogleOAuthProvider} from "@react-oauth/google";
import {AuthProvider} from "@/context/AuthContext";
import {ReactNode} from "react";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Mangoberry",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <GoogleOAuthProvider clientId="387957433864-cis9fl5ju31oj0bo56v8d6oiatmj173b.apps.googleusercontent.com">
            <AuthProvider> {/* ✅ 로그인 상태 전역 관리 */}
                {children}
            </AuthProvider>
        </GoogleOAuthProvider>
        </body>
        </html>
    );
}
